### ISSUE TITLE
API not Working

### ISSUE THREAD

**Issue by kjcp** [kuzmany/mautic-prestashop#1]
Hi, Im running prestashop 1.6.x, and mautic version 2.8.2

I downloaded the module corresponding to prestashop 1.6.x and follow the documentation for configuration. However, even though my prestashop back office for mautic configuration says "Access token are valid" I am unable to see any fields from mautic in order to add CUSTOMER TRAKING, GUEST TRAKING or any other field for mapping like list mapping and field mapping.

Please help!

**Comment by pprietoa** [comment]
Hi, exact same issue here, please let me know if you find a fix.

Thanks

**Comment by kuzmany** [comment]
I can't help. It's open source, everybody can update it, hire programmer for new features etc. 
If you can donate, I can look on it.

**Comment by nikosnik** [comment]
Hi, 

Same problem here. 
@kuzmany 
Open source does not mean you provide a broken piece of software and refuse to even look at it. This is not a feature request, it is a bug. It is your responability to fix it (if you care about your work or your good name at the least). 
Or you can state with big fat letters "this project is dead! I will only responed if you pay me" 
I was seriously thinking about donating on one of your projects on https://mautic-fund.kuzmany.biz/ but with this attidude I am don't see the point. 

Hope you change your mind

**Comment by nikosnik** [comment]
WOW!!! That's a first! You simply deleted my comment instead of answering . you don't even give a reason for it.  What a nice guy!

**Comment by kuzmany** [comment]
@nikosnik no big deal man. Just your comment was offensive and disrespectful to hundreds and hundreds hours of my free time for people and their business.   I gave 2 solutions: wait for my fix (my free time -no free time now) or hire somebody. I counted several insults from you comment.

**Comment by nikosnik** [comment]
@kuzmany
Please repost my message and comment on WHERE  insulted you. Because 1. I never indented to insult you and 2.   you are disrespectful to ME when you simply deleted my comment and not even telling me why. 
You never gave 2 options. 
You said 
`I can't help` 
'hire programmer'  and
'If you can donate, I can look on it.' 
Where are you saying that you even will look at it when you have free  time?
As I understand it you first made this as a commercial module and you sold it. So you got paid for your time (the amount is not the  issue)then you release it as open source (and I congratulate you for this). Now some users complain about a bug. My many years in Open source have told me that a developer listen to the users who are trying to help by reporting a bug.  If your code is good it should not take you more than an hour to debug it. If you need help please ask and we (I) will gladly help to my ability. This is the most common way to get things done in OS
Sorry for my long post.

P.S When you are saying Donation, what amount would be good for you? But keep in mind that then this is a commercial product and not OS and I (we) will expect further support from you with no extra charge

**Comment by kuzmany** [comment]
@nikosnik added statement to readme. 
Sorry I am tired for argue. I respect your opinion, I just have different attitude. Module was release time ago  and I don't have free time for maintaining now. This module don't pay my bill  👍  
Thank you for undertanding

**Comment by phgeek** [comment]
Hi,
I'm using almost latest version of both softwares. PS 1.7.2.4 & Mautic 2.9.2.
I got it fixed by simply clearing Mautic's cache:
`$ rm -fR MAUTIC_ROOT/app/cache/*`

Still have a empty alert at top of settings but no more empty lists.

**Comment by kuzmany** [comment]
Sorry guys, I don't have time for improve this plugin. 
But as @phgeek  said.  yes try clear Mautic cache. 
Month ago I installed plugint and works.

**Comment by klevisndoka** [comment]
It worked by clearing Mautic cache.
